POST http://localhost:5000/users
Content-Type : application/json

{
    "firstName" : "Farsit",
    "lastName"  : "Kalam",
    "email" : "robayatfarsit10@gmail.com",
    "password" : "Farsit@2025"
}


POST http://localhost:5000/users/create-many
Content-Type : application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoicm9iYXlhdGZhcnNpdDEwQGdtYWlsLmNvbSIsImlhdCI6MTc1ODI2NTY0MiwiZXhwIjoxNzU4MjY5MjQyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDo1MDAwIn0.BoDu1i9xExbuKGCX-mR9kzm7ji1ZDDhESM94Ucoj76M

{
    "users" : [
    {
    "firstName" : "Farsit",
    "lastName"  : "Kalam",
    "email" : "robayatfarsit1@gmail.com",
    "password" : "Farsit@2025"
},
{
    "firstName" : "Farsit1",
    "lastName"  : "Kalam",
    "email" : "robayatfarsit2@gmail.com",
    "password" : "Farsit@2025"
},
{
    "firstName" : "Farsit2",
    "lastName"  : "Kalam",
    "email" : "robayatfarsit3@gmail.com",
    "password" : "Farsit@2025"
},
{
    "firstName" : "Farsit3",
    "lastName"  : "Kalam",
    "email" : "robayatfarsit4@gmail.com",
    "password" : "Farsit@2025"
}
]
}